create domain if not exists jsonb as json;
alter table projects add column if not exists request_text clob;
alter table projects add column if not exists current_stage varchar(50);
alter table projects add column if not exists current_outline_version_id uuid;
alter table projects add column if not exists page_count_target integer;
alter table projects add column if not exists style_preset varchar(100);
alter table projects add column if not exists background_asset_path varchar(1000);
alter table projects add column if not exists workflow_constraints_json jsonb;

create table if not exists requirement_forms (
    id uuid primary key,
    project_id uuid not null unique,
    status varchar(50) not null,
    based_on_outline_version_id uuid null,
    summary_md clob null,
    outline_context_md clob null,
    fixed_items_json jsonb null,
    init_search_queries_json jsonb null,
    init_search_results_json jsonb null,
    init_corpus_digest_json jsonb null,
    ai_questions_json jsonb null,
    answers_json jsonb null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists project_messages (
    id uuid primary key,
    project_id uuid not null,
    stage varchar(50) not null,
    scope_type varchar(50) not null,
    target_page_id uuid null,
    role varchar(50) not null,
    content_md clob not null,
    structured_payload_json jsonb null,
    created_at timestamp with time zone not null
);

create table if not exists project_events (
    stream_id bigint generated by default as identity primary key,
    event_id uuid not null unique,
    project_id uuid not null,
    event_type varchar(100) not null,
    stage varchar(50) not null,
    scope_type varchar(50) not null,
    target_page_id uuid null,
    agent_run_id uuid null,
    payload_json jsonb null,
    created_at timestamp with time zone not null
);

create table if not exists outline_versions (
    id uuid primary key,
    project_id uuid not null,
    version_no integer not null,
    status varchar(50) not null,
    parent_version_id uuid null,
    outline_json jsonb not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_outline_versions_project_version unique (project_id, version_no)
);

create table if not exists project_pages (
    id uuid primary key,
    project_id uuid not null,
    page_code varchar(100) not null,
    page_role varchar(100) null,
    part_title varchar(255) null,
    sort_order integer not null,
    current_brief_version_id uuid null,
    current_research_session_id uuid null,
    current_draft_version_id uuid null,
    current_design_version_id uuid null,
    outline_status varchar(50) not null,
    search_status varchar(50) not null,
    summary_status varchar(50) not null,
    draft_status varchar(50) not null,
    design_status varchar(50) not null,
    artifact_staleness_json jsonb null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_project_pages_project_code unique (project_id, page_code)
);

create table if not exists page_brief_versions (
    id uuid primary key,
    project_id uuid not null,
    page_id uuid not null,
    version_no integer not null,
    status varchar(50) not null,
    parent_version_id uuid null,
    section_title varchar(255) null,
    title varchar(255) not null,
    content_outline_json jsonb not null,
    content_summary clob null,
    self_check_result_json jsonb null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_page_brief_versions_page_version unique (page_id, version_no)
);

create table if not exists draft_versions (
    id uuid primary key,
    project_id uuid not null,
    page_id uuid not null,
    version_no integer not null,
    status varchar(50) not null,
    page_brief_version_id uuid null,
    research_session_id uuid null,
    draft_svg_markup clob null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_draft_versions_page_version unique (page_id, version_no)
);

create table if not exists design_versions (
    id uuid primary key,
    project_id uuid not null,
    page_id uuid not null,
    version_no integer not null,
    status varchar(50) not null,
    draft_version_id uuid null,
    style_pack_id varchar(100) null,
    background_asset_path varchar(1000) null,
    design_svg_markup clob null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_design_versions_page_version unique (page_id, version_no)
);

create table if not exists project_stage_runs (
    id uuid primary key,
    project_id uuid not null,
    stage varchar(50) not null,
    attempt_no integer not null,
    status varchar(50) not null,
    input_refs_json jsonb null,
    output_ref_json jsonb null,
    error_message clob null,
    started_at timestamp with time zone not null,
    finished_at timestamp with time zone null,
    constraint uk_project_stage_runs_attempt unique (project_id, stage, attempt_no)
);

create table if not exists page_stage_runs (
    id uuid primary key,
    project_id uuid not null,
    page_id uuid not null,
    stage varchar(50) not null,
    attempt_no integer not null,
    status varchar(50) not null,
    input_refs_json jsonb null,
    output_ref_json jsonb null,
    error_message clob null,
    started_at timestamp with time zone not null,
    finished_at timestamp with time zone null,
    constraint uk_page_stage_runs_attempt unique (page_id, stage, attempt_no)
);

create table if not exists bocha_search_cache (
    id uuid primary key,
    query_key varchar(200) not null unique,
    query_text clob not null,
    provider varchar(50) not null,
    result_json jsonb null,
    result_count integer not null,
    expires_at timestamp with time zone null,
    created_at timestamp with time zone not null
);

create table if not exists url_content_cache (
    id uuid primary key,
    normalized_url varchar(1000) not null unique,
    provider varchar(50) not null,
    title varchar(500) null,
    markdown_content clob null,
    metadata_json jsonb null,
    content_hash varchar(128) null,
    status varchar(50) not null,
    expires_at timestamp with time zone null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists source_collections (
    id uuid primary key,
    project_id uuid not null,
    page_id uuid null,
    collection_type varchar(50) not null,
    title varchar(255) not null,
    created_at timestamp with time zone not null
);

create table if not exists source_documents (
    id uuid primary key,
    collection_id uuid not null,
    source_type varchar(50) not null,
    source_uri varchar(1000) not null,
    url_cache_id uuid null,
    title varchar(500) null,
    markdown_content clob null,
    metadata_json jsonb null,
    content_hash varchar(128) null,
    status varchar(50) not null,
    created_at timestamp with time zone not null
);

create table if not exists source_chunks (
    id uuid primary key,
    source_document_id uuid not null,
    chunk_index integer not null,
    section_path varchar(500) null,
    content_md clob not null,
    content_for_embedding clob not null,
    embedding clob null,
    token_count integer not null,
    created_at timestamp with time zone not null,
    constraint uk_source_chunks_doc_index unique (source_document_id, chunk_index)
);

create table if not exists research_sessions (
    id uuid primary key,
    project_id uuid not null,
    page_id uuid null,
    scope_type varchar(50) not null,
    session_role varchar(50) not null,
    page_brief_version_id uuid null,
    based_on_session_id uuid null,
    research_goal clob null,
    query_plan_json jsonb null,
    summary_md clob null,
    key_findings_json jsonb null,
    overlap_risks_json jsonb null,
    open_questions_json jsonb null,
    status varchar(50) not null,
    confirmed_by_message_id uuid null,
    context_snapshot_json jsonb null,
    candidate_sources_json jsonb null,
    selected_citations_json jsonb null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists research_sources (
    id uuid primary key,
    research_session_id uuid not null,
    title varchar(500) null,
    url varchar(1000) null,
    snippet clob null,
    provider_rank integer null,
    raw_payload_json jsonb null,
    created_at timestamp with time zone not null
);

create table if not exists research_session_sources (
    id uuid primary key,
    research_session_id uuid not null,
    source_document_id uuid null,
    chunk_id uuid null,
    rank_no integer not null,
    excerpt_md clob null,
    relevance_score double precision null,
    usage_note varchar(500) null,
    is_pinned boolean not null default false,
    constraint uk_research_session_sources_session_chunk unique (research_session_id, chunk_id)
);

create table if not exists retrieval_runs (
    id uuid primary key,
    project_id uuid not null,
    research_session_id uuid null,
    query_text clob not null,
    retrieval_mode varchar(50) not null,
    status varchar(50) not null,
    created_at timestamp with time zone not null
);

create table if not exists retrieval_candidates (
    id uuid primary key,
    retrieval_run_id uuid not null,
    source_document_id uuid null,
    chunk_id uuid null,
    score_vector double precision null,
    score_keyword double precision null,
    score_final double precision null,
    selected boolean not null default false
);

create table if not exists citations (
    id uuid primary key,
    project_id uuid not null,
    page_id uuid null,
    research_session_id uuid null,
    source_document_id uuid null,
    chunk_id uuid null,
    title varchar(500) null,
    url varchar(1000) null,
    excerpt_md clob null,
    citation_label varchar(100) not null,
    created_at timestamp with time zone not null,
    constraint uk_citations_page_chunk_label unique (project_id, page_id, chunk_id, citation_label)
);
